repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml

-   repo: local
    hooks:
    -   id: prettier
        name: Prettier Format
        entry: pixi run format
        language: system
        pass_filenames: false

    -   id: eslint
        name: ESLint
        entry: pixi run lint
        language: system
        pass_filenames: false
